/**
 * Vendor the declarative agent-preset rows shipped by the host's
 * @deepseek-ai/dsh-web-app bundle into src/bridge/presetPatches.ts.
 *
 * DSH 0.1.7 replaced the self-contained dsh-agent-presets service (shipped
 * roster) with YAML-declared preset rows; the acp composition carries none,
 * so the acp-vscode profile must declare them to keep the preset picker.
 * Re-run after a host bump:
 *
 *   node scripts/sync-presets.mjs [path-to-deepseek-harness]
 *
 * Default source: ~/deepseek-harness (must sit at the targeted tag).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join } from 'node:path'

const repo = process.argv[2] ?? `${process.env.HOME}/deepseek-harness`
const tag = execSync('git describe --tags', { cwd: repo, encoding: 'utf8' }).trim()
const ids = ['standard', 'ptc', 'minimal', 'cordis']

const header = `/**
 * GENERATED by scripts/sync-presets.mjs from ${tag}
 * (packages/bundle/web-app/presets/*.patch.yml) — do not edit by hand.
 *
 * The agent-preset rows the acp-vscode profile needs on DSH ≥ 0.1.7: the
 * registry row plus one \`dsh-agent-preset\` declaration per shipped preset
 * (the same roster the removed dsh-agent-presets package carried on 0.1.5).
 * The 0.1.7 host tolerates a stale copy per-preset: an unresolvable row
 * fails its own mount and surfaces as a broken roster entry, never as a
 * composition failure.
 */`

const registry = `# The preset selection registry (the acp composition carries no preset rows).
- insert:
    - id: agent-preset-registry
      name: '@deepseek-ai/dsh-agent-preset-registry'
      config:
        default: standard
`

// Normalize: exactly one trailing newline per part so the concatenation embeds
// cleanly into the installer's heredoc (whose terminator must start a line).
const norm = (s) => s.trimEnd() + '\n'
const body = [registry, ...ids.map(id => norm(readFileSync(join(repo, 'packages/bundle/web-app/presets', `${id}.patch.yml`), 'utf8')))].join('\n')

const out = `${header}
export const AGENT_PRESET_PATCH_YML = ${JSON.stringify(body)}
`
writeFileSync(new URL('../src/bridge/presetPatches.ts', import.meta.url), out)
console.log(`vendored ${ids.length} preset declarations from ${tag} (${body.length} chars)`)
